[package]
name = "rcl-sys"
version = "0.1.0"
authors = ["nnmm <nnmmgit@gmail.com>"]
edition = "2018"
links = "rcl"
build = "build.rs"

[lib]
name = "rcl_sys"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
bindgen = "0.45.0"